### ISSUE TITLE
Todo List (Minh + Saloni)

### ISSUE THREAD

**Issue by cassandrale179** [cassandrale179/ci491_project#2]
# AUTH SYSTEM
- [x] Link Firebase to the App  @cassandrale179  

## Splash screen + Identification Screen
- [x] Create splash screen front end @cassandrale179  
- [x] Transition from Splash -> Identification Screen Activity @cassandrale179 
- [x]  Create Identification Screen (front-end) @cassandrale179 
- [x] Transition from Identification Screen -> Signup with state storage @cassandrale179 

## Signup Page 
- [x] Create sign up system (front-end) @cassandrale179 
- [ ] Create sign up system (backend) @cassandrale179 
- [ ] Add in error handling for signup page @cassandrale179 
- [ ] Add in page transitioning into Match Page @cassandrale179  

## Login Page 
- [ ] Create login system (front-end) @Sppurswani  
- [ ] Create login system (back-end) @Sppurswani 
- [ ] Add in error handling (if user email and password isn't found in database - Firebase Auth should handle this for you) @Sppurswani 

## Match Request page 
- [ ] Send email verification to people @Sppurswani 
- [ ] Build the front-end for match page @cassandrale179 

## App
- [x] Switch the MainActivity to redirect to splash screen instead of Home Screen @cassandrale179 
- [x] change color on the app (primary + secondary) @cassandrale179
